-- Insert FKKMMBT Structure Data
INSERT INTO struktur_organisasi (nama, jabatan, level, urutan, jenis_kelamin, kontak, foto) VALUES
('Aceva Arie Sadewa', 'Ketua Umum', 1, 1, 'L', '6287786720942', NULL),
('Ahmad Fauzi', 'Wakil Ketua Umum', 2, 2, 'L', NULL, NULL),
('Siti Nurhaliza', 'Sekretaris I', 3, 3, 'P', NULL, NULL),
('Dewi Kartika', 'Sekretaris II', 3, 4, 'P', NULL, NULL),
('Budi Santoso', 'Bendahara I', 3, 5, 'L', NULL, NULL),
('Rina Wati', 'Bendahara II', 3, 6, 'P', NULL, NULL),
('Andi Pratama', 'Divisi Kepemudaan', 4, 7, 'L', NULL, NULL),
('Riko Saputra', 'Divisi Kepemudaan', 4, 8, 'L', NULL, NULL),
('Dimas Arya', 'Divisi Kreatif', 4, 9, 'L', NULL, NULL),
('Maya Putri', 'Divisi Kreatif', 4, 10, 'P', NULL, NULL),
('Hendra Kurniawan', 'Divisi Humas', 4, 11, 'L', NULL, NULL),
('Linda Safitri', 'Divisi Humas', 4, 12, 'P', NULL, NULL),
('Yoga Pratama', 'Divisi Olahraga', 4, 13, 'L', NULL, NULL),
('Faisal Rahman', 'Divisi Olahraga', 4, 14, 'L', NULL, NULL),
('Surya Wijaya', 'Divisi Teknologi', 4, 15, 'L', NULL, NULL),
('Fikri Ramadhan', 'Divisi Teknologi', 4, 16, 'L', NULL, NULL),
('Indah Permata', 'Divisi Sosial', 4, 17, 'P', NULL, NULL),
('Ayu Lestari', 'Divisi Sosial', 4, 18, 'P', NULL, NULL),
('Bayu Setiawan', 'Divisi Keamanan', 4, 19, 'L', NULL, NULL),
('Doni Saputra', 'Divisi Keamanan', 4, 20, 'L', NULL, NULL),
('Eka Putri', 'Divisi Kewanitaan', 4, 21, 'P', NULL, NULL),
('Nur Azizah', 'Divisi Kewanitaan', 4, 22, 'P', NULL, NULL);
